# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch


# Create random tensor
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.1094, 0.0241, 0.3079, 0.9415, 0.4867, 0.8540, 0.5736],
        [0.8424, 0.2722, 0.7943, 0.5405, 0.5880, 0.2523, 0.9398],
        [0.1956, 0.1491, 0.2430, 0.4032, 0.4433, 0.2146, 0.7387],
        [0.1582, 0.9156, 0.0887, 0.1453, 0.2719, 0.8615, 0.3210],
        [0.2944, 0.3562, 0.6530, 0.4353, 0.7871, 0.0330, 0.5902],
        [0.9408, 0.5730, 0.9869, 0.8010, 0.9083, 0.5753, 0.3293],
        [0.3991, 0.9886, 0.2404, 0.6149, 0.1921, 0.5179, 0.5561]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [18]:
# Create another random tensor
second_rand_tensor =  torch.rand(1,7)
second_rand_tensor

# Perform matrix multiplication
transposed = torch.transpose(second_rand_tensor,0,1) # second_rand_tensor.T
transposed

torch.mm(rand_tensor, transposed)

tensor([[2.6580],
        [2.7139],
        [1.8114],
        [2.2227],
        [2.1921],
        [3.2393],
        [2.6318]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)

# Create two random tensors
first = torch.rand(7,7)
second = torch.rand(1,7).T

# Matrix multiply tensors
torch.mm(first, second)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [23]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)

t1_on_gpu = t1.to('cuda')
t2_on_gpu = t2.to('cuda')
t1_on_gpu, t2_on_gpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [33]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(t1_on_gpu, t2_on_gpu.T)
res, res.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [37]:
# Find max
res_max = res.max()

# Find min
res_min = res.min()
print(f'Max: {res_max}, Min: {res_min}')


Max: 0.5617256760597229, Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
res_argmax = res.argmax()

# Find arg min
res_argmin = res.argmin()

print(f'Argmax: {res_argmax}, Argmin: {res_argmin}')

Argmax: 3, Argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [43]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t = torch.rand(1,1,1,10)

# Remove single dimensions
t_squeezed = t.squeeze()

# Print out tensors and their shapes
t, t.shape, t_squeezed, t_squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))